### ISSUE TITLE
Правки и дополнения по роутам

### ISSUE THREAD

**Issue by antoniocra04** [antoniocra04/it-academy-hackaton-2024-back#22]
> [!WARNING]
> Переименовать GetUserToId в GetUserById

> [!WARNING]
> Удалить WeatherForecast

> [!WARNING]
> После авторизации и регистрации должен возвращатся пользователь вместе с группами и мероприятиями в которых он участвует

> [!WARNING]
> У клуба нет полного описания, есть только description

> [!WARNING]
> Создать роут для вступление и выхода из клуба

> [!WARNING]
> В GetAllClubs не возвращается колличество участников

> [!WARNING]
> При попытке создания одинаковых пользователей в signUp возвращать не просто 400, а еще текст ошибки "Такой пользователь уже существует"

> [!WARNING]
> При отправке неправильных данных в роуте login возвращать сообщение "Введен неправильный пароль, либо такого пользователя не существует"

> [!WARNING]
> Созадать роут удаления пользователя от лица админа, принимает логин и пароль админа, логин пользователя которого нужно удалить

> [!WARNING]
> Добавить хеширование пароля и jwt токен в котором будет хранится вся информация о пользователе кроме пароля. Срок действия - бессрочный

**Comment by VGorHub** [comment]
А зачем тебе клубы и мероприятия пользователя после регистрации ?

**Comment by VGorHub** [comment]
"У клуба нет полного описания, есть только description " - типо добавить FullDescription  полное описание ?

**Comment by antoniocra04** [comment]
> А зачем тебе клубы и мероприятия пользователя после регистрации ?

Для того чтобы в профиле отобразить группы и мероприятия в которых участвует пользователь

**Comment by antoniocra04** [comment]
> "У клуба нет полного описания, есть только description " - типо добавить FullDescription полное описание ?

Да

**Comment by VGorHub** [comment]
> > А зачем тебе клубы и мероприятия пользователя после регистрации ?
> 
> Для того чтобы в профиле отобразить группы и мероприятия в которых участвует пользователь

Так после того как он зарегистрируется у него не может быть не клубов ни Ивентов в которых он участвует

**Comment by VGorHub** [comment]
И ещё при вступлении в клуб ты на вход подаешь логин пароль пользователя и айди клуба куда вступить ?

или айди пользователя и айди клуба ?

**Comment by antoniocra04** [comment]
> > > А зачем тебе клубы и мероприятия пользователя после регистрации ?
> > 
> > 
> > Для того чтобы в профиле отобразить группы и мероприятия в которых участвует пользователь
> 
> Так после того как он зарегистрируется у него не может быть не клубов ни Ивентов в которых он участвует

Тогда в авторизации и getUserById

**Comment by antoniocra04** [comment]
> И ещё при вступлении в клуб ты на вход подаешь логин пароль пользователя и айди клуба куда вступить ?
> 
> или айди пользователя и айди клуба ?

Логин, пароль и айди клуба

**Comment by VGorHub** [comment]
"В GetAllClubs не возвращается колличество участников" - а ты не можешь сам чтоль посчитать там тебе список возвращается ?И может создать отдельный роут под это ?

**Comment by VGorHub** [comment]
> "В GetAllClubs не возвращается колличество участников" - а ты не можешь сам чтоль посчитать там тебе список возвращается ?И может создать отдельный роут под это ?

Забей это оказалось легко реализовать в 1 роуте

**Comment by VGorHub** [comment]
Вроде сделал JWT токены.Зайди на мою ветку потести так это должно работать или нет.Осталось сделать хеширование пароля, но я за сегодня устал поэтому сделаю завтра.

**Comment by antoniocra04** [comment]
В место юзера в токене вот это
![image](https://github.com/antoniocra04/it-academy-hackaton-2024-back/assets/40686374/6e230100-8559-4527-b067-5bd99f8d02c6)

**Comment by VGorHub** [comment]
А ну и вопрос что мне хранить в JWT токене.Я сомневаюсь что я там смогу хранить список клубов или список ивентов.Я глянул он там ток string переменные хранит.Как мне списки то в нем хранить.Как вариант я могу там хранить все кроме этого и в ответ тебе присылать json где 1 это будет сам токен 2 это список клубов как ещё 1 json объект и 3 это список ивентов.

**Comment by antoniocra04** [comment]
Так, тогда давай все кроме ивентов и клубов, а их я тогда буду отдельно запрашивать

**Comment by VGorHub** [comment]
И ещё вопрос по хэшированию пароля получается ты присылаешь пароль я его хэширую и храню хэш в БД(Это при регистрации) а потом когда ты будешь ещё присылать пароль для входа я его буду тоже хэшировать и сравнивать с хэшем в БД ?

**Comment by antoniocra04** [comment]
в дс зайди
